name: movie_app
description: "A Flutter project movie app"
version: 1.0.0+1
environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.1
  flutter_animate: ^4.5.2
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.2
  firebase_auth: ^5.4.1
  flutter_riverpod: ^2.6.1
  http: ^1.3.0
  readmore: ^3.0.0
  webview_flutter: ^4.10.0
  image_picker: ^1.1.2
  shared_preferences: ^2.5.1
  shimmer: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
  - assets/icons/
  - assets/imgs/